### PR TITLE
AMW-278 Adding JBoss Network API secrets to run Ansible demo successfully

### PR DESCRIPTION
**Pull request by RanabirChakraborty**
Issue: https://issues.redhat.com/browse/AMW-278

### CODE REVIEW

**Review by rpelisse — CHANGES_REQUESTED** [review]
@RanabirChakraborty Rather than adding this variable there, I think you should use directly the molecule_downstream.sh. Did you try that first?

**Comment by RanabirChakraborty** [comment]
yes @rpelisse I have tried using it but it was not processing, and plus molecule.sh was already working fine so added the creds only.

**Comment by rpelisse** [comment]
Can you elaborate on what was failing with the downstream-molecule? Because, if we start moving "downstream logic" (and for sure API is downstream logic) into the upstream, it's going to be confusing...

**Comment by RanabirChakraborty** [comment]
It'll require `LAST_SUCCESS_FULL_BUILD_ID`, `PROJECT_UPSTREAM_NAME` and also parent job details to run with molecule_downstream.sh. (details - ansible-eap-migration-demo/63)

**Comment by rpelisse** [comment]
Hum... :thinking: 

Yeah, in this case, we should modify the downstream-molecule.sh to skip those parts if not relevant, but that's too much work for now, so let's go for your option!

**Pull request merged**
