### PR TITLE
Renaming upgrade-component test script from .sh to .bats

### PR DESCRIPTION
**Pull request by TomasHofman**
...to include upgrade-components-report tests automatically when running `bats -t tests/`.

* Add mention how tun the TS to readme.
* Send report in email body rather than an attachment.

### CODE REVIEW

**Comment by rpelisse** [comment]
@TomasHofman Yes, I saw that. I was planning to explore the option of mail. I am pretty sure we can have the command send the report as body, without using cat.

**Comment by TomasHofman** [comment]
@rpelisse just wanted to message you about it, I know it's perhaps not the nicest solution, but I would prefer to have it as it's better from UX perspective. We can leave this PR open and improve it before merging, I'm still doing some experiments with Jenkins jobs, and I'm not consuming the script from github ATM.

I'm going to be off for the rest of the week BTW, hopefully be back next week.

**Comment by TomasHofman** [comment]
The only other way I found is the other kind of redirection:

```$ mail -s "Hello World" user@yourmaildomain.com < /home/user/mailcontent.txt```

:)

**Comment by rpelisse** [comment]
But of course! I always forgot about this redirection trick. I'm pretty sure it's not the first time I've researched how to pass content as body with mail and found about this solution. Darn. Anyhow, I would prefer this redirection solution if it's OK with you. Can you update the PR accordingly?

**Comment by TomasHofman** [comment]
Okey, will update.

**Comment by TomasHofman** [comment]
@rpelisse I'm gonna merge this if you have no objections.

**Comment by rpelisse** [comment]
@TomasHofman done!

**Pull request merged**
