### PR TITLE
[SET-447] Update CRYO_HARMONIA_SSH to eap-job/olympus.sh

### PR DESCRIPTION
**Pull request by gaol**
Issue: https://issues.redhat.com/browse/SET-447

### CODE REVIEW

**Comment by gaol** [comment]
@rpelisse @spyrkob would you please review ? thanks

**Review by spyrkob — APPROVED** [review]
LGTM

**Comment by rpelisse** [comment]
@gaol LGTM too!

**Review by rpelisse — APPROVED** [review]

**Comment by rpelisse** [comment]
@gaol LGTM too!

**Pull request merged**
